### ISSUE TITLE
improvement in ui

### ISSUE THREAD

**Issue by Swapnil-2503** [Swapnil-2503/allgames#1]
![Screenshot 2023-06-04 170900](https://github.com/Swapnil-2503/allgames/assets/89910173/03e94cdc-8c72-4ebd-936c-a8f319f05235)
Change this ui with some aesthetics and add animations if required

**Comment by Abraham12611** [comment]
Hello 👋

I would like to help.
So how do I get started?

**Comment by Swapnil-2503** [comment]
I want to make it look good, I made this issue for contributions so your task is to make it look cool.
See here i made a list of games and buttons you can do it like after hover the button it will show that description of game .
👍

**Comment by Abraham12611** [comment]
Okay, I would start working on it now.

**Comment by Abraham12611** [comment]
I was thinking, what if I added an image at the background and then when the the user hovers with a mouse it shows a description of the game and the Link.

**Comment by Swapnil-2503** [comment]
Good thinking, So you want to make it more animated that will be cool
